data_dir: _data
mathjax: true

# Site settings
name: Onther's Publications
email: info@onther.io
author: Onther Inc.
url: https://blog.onther.io
resume_site: https://blog.onther.io
github: https://github.com/Onther-Tech/
facebook: https://www.facebook.com/OntherInc/
linkedin: https://www.linkedin.com/company/onther-tech/
telegram: https://t.me/onther_blockchain
twitter: https://twitter.com/ontherInc
youtube: https://www.youtube.com/c/OntherInc
blog_github : https://github.com/Onther-Tech/publications
baseurl: ""
description: 이더리움 블록체인 R&D 스타트업 온더의 블로그
meta_description: 이더리움 블록체인 스타트업 온더의 블로그
motto: If you can't measure it—it doesn't exist.
banner: 블록체인이란 사회적 비용을 줄이기 위해 컴퓨팅 비용을 희생하는법에 관한 것이다 - V. Buterin
donation : 0x4D5F880c27A0328490A83BF12760892d4CC7E5f9

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:categories/:title/
paginate:

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: ggs134

# Build settings
markdown: kramdown

#eric
kramdown:
   math_engine: mathjax

# baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
